@startuml c4-container-modulith-without-creditinstitute

title Container Diagram for T2-Modulith

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Icons (https://github.com/tupadr3/plantuml-icon-font-sprites)
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master
!include ICONS/common.puml
!include ICONS/devicons2/spring.puml
!include ICONS/devicons2/mongodb.puml
!include ICONS/devicons2/postgresql.puml

AddElementTag("db", $bgColor="#MidnightBlue", $legendText="database")
AddElementTag("external", $bgColor="#Gray", $legendText="external")

System_Boundary(t2_project, "T2-Modulith") {

    Container(modulith, "Modulith", "Java, Spring MVC", $sprite="spring")

    ContainerDb(db_inventory, "Inventory Database", "PostgreSQL", $sprite="postgresql", $tags="db")
    ContainerDb(db_cart_and_order, "Cart and Order Database", "MongoDB", $sprite="mongodb", $tags="db")
}

Rel(modulith, db_cart_and_order, "R&W", "TCP")
Rel(modulith, db_inventory, "R&W", "JDBC")

@enduml
