@startuml c4-container-microservices-simplified

title Container Diagram for T2-Microservices (simplified)

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Icons (https://github.com/tupadr3/plantuml-icon-font-sprites)
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master
!include ICONS/common.puml
!include ICONS/devicons2/spring.puml
!include ICONS/devicons2/mongodb.puml
!include ICONS/devicons2/postgresql.puml

' AddElementTag("saga", $bgColor="#SlateBlue", $legendText="saga")

System_Boundary(t2_project, "Microservices") {

    Container(uibackend, "UIBackend", "Java, Spring MVC", $sprite="spring")
    Container(ui, "UI", "Java, Spring MVC, JSP", $sprite="spring")
    Container(inventory, "Inventory", "Java, Spring MVC", $sprite="spring", $tags="saga")
    Container(orchestrator, "Orchestrator", "Java, Spring MVC", $sprite="spring", $tags="saga")
    Container(payment, "Payment", "Java, Spring MVC", $sprite="spring", $tags="saga")
    Container(order, "Order", "Java, Spring MVC", $sprite="spring", $tags="saga")
    Container(cart, "Cart", "Java, Spring MVC", $sprite="spring")
}

Rel_Neighbor(ui, uibackend, "Uses", "JSON/HTTP")
Rel(uibackend, cart, "Uses", "JSON/HTTP")
Rel(uibackend, orchestrator, "Uses", "JSON/HTTP")
Rel(uibackend, inventory, "Uses", "JSON/HTTP")
Rel(orchestrator, inventory, "Uses", "JSON/HTTP")
Rel(orchestrator, order, "Uses", "JSON/HTTP")
Rel(orchestrator, payment, "Uses", "JSON/HTTP")

@enduml
