@startuml c4-container-modulith-with-users

title Container Diagram for T2-Modulith

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Icons (https://github.com/tupadr3/plantuml-icon-font-sprites)
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master
!include ICONS/common.puml
!include ICONS/devicons2/spring.puml
!include ICONS/devicons2/mongodb.puml
!include ICONS/devicons2/postgresql.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_WITH_LEGEND()

Person(user, "User", "Buys tea using the UI of the store.")
Person(researcher, "Researcher", "Executes various tests using the API's of the store.")

System_Boundary(t2_project, "T2-Modulith") {

    Container(modulith, "Modulith", "Java, Spring MVC", $sprite="spring")

    ContainerDb(db_inventory, "Inventory Database", "PostgreSQL", $sprite="postgresql")
    ContainerDb(db_cart_and_order, "Cart and Order Database", "MongoDB", $sprite="mongodb")
}

Container_Ext(creditinstitute, "CreditInstitute", "Java, Spring MVC", $sprite="spring")

Rel(researcher, modulith, "Uses", "JSON/HTTP")
Rel(user, modulith, "Uses", "JSON/HTTP")

Rel(modulith, db_cart_and_order, "Reads from /\nwrites to", "TCP")
Rel(modulith, db_inventory, "Reads from /\nwrites to", "JDBC")

Rel(modulith, creditinstitute, "Makes\ncalls to", "JSON/HTTP")
@enduml
