@startuml c4-component-modulith-simplified

title Component Diagram for T2-Modulith (simplified)

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' Icons (https://github.com/tupadr3/plantuml-icon-font-sprites)
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master
!include ICONS/common.puml
!include ICONS/devicons2/spring.puml
!include ICONS/devicons2/mongodb.puml
!include ICONS/devicons2/postgresql.puml

top to bottom direction

Container_Boundary(modulith, "Modulith", "Java, Spring MVC") {
    Component(uibackend, "UIBackend", "Module")
    Component(ui, "UI", "Module")
    Component(inventory, "Inventory", "Module")
    Component(order, "Order", "Module")
    Component(payment, "Payment", "Module")
    Component(cart, "Cart", "Module")
}

Rel_Neighbor(ui, uibackend, "Uses")
Rel(uibackend, cart, "Uses")
Rel(uibackend, order, "Uses")
Rel(uibackend, inventory, "Uses")
Rel(order, inventory, "Uses")
Rel(order, payment, "Uses")
Rel(order, cart, "Uses")

@enduml
