@startuml c4-deployment-measurement-setup-kepler-simplified-3

' title Measurement Setup - EKS & Kepler (Simplified)

' C4 (https://github.com/plantuml-stdlib/C4-PlantUML/)
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' Icons (https://github.com/tupadr3/plantuml-icon-font-sprites)
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define WEATHER https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/weather
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/common.puml
!include WEATHER/day_sunny.puml
!include FONTAWESOME/tools.puml
!include FONTAWESOME/file_alt.puml
!include FONTAWESOME/file_medical_alt.puml
!include FONTAWESOME/bullseye.puml
!include FONTAWESOME/desktop.puml
!include FONTAWESOME/chart_bar.puml
!include FONTAWESOME/mug_hot.puml
!include DEVICONS2/kubernetes.puml
!include DEVICONS2/java.puml

' Logos from Cloudogu EcoSystem (https://github.com/cloudogu/plantuml-cloudogu-sprites)
!define CloudoguPuml https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!define ENTITY(e_type,e_color,e_sprite,e_alias,e_stereo) e_type "<color:e_color><$e_sprite></color>" as e_alias <<e_stereo>>
!define ENTITY(e_type,e_color,e_sprite,e_label,e_alias,e_stereo) e_type "<color:e_color><$e_sprite></color>\r e_label" as e_alias <<e_stereo>>
!include CloudoguPuml/tools/grafana.puml
!include CloudoguPuml/tools/prometheus.puml

' Kubernetes icons (https://github.com/dcasati/kubernetes-PlantUML)
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist
!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/OSS/KubernetesKubelet.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesHpa.puml

left to right direction
skinparam ArrowFontSize 16

AddElementTag("jmeter", $bgColor="#d22128")
AddElementTag("k8s", $bgColor="#316ce6")
AddElementTag("kepler", $bgColor="#00766a")
AddElementTag("grafana", $bgColor="#f39f5f")
AddElementTag("prometheus", $bgColor="#e8613e")
' AddElementTag("sut", $bgColor="LightYellow")

Deployment_Node(local, "Local Machine", "", $sprite="desktop") {

    Container(jmeter, "JMeter", "", "", $sprite="java", $tags="jmeter")
}

Deployment_Node(eks, "Kubernetes", "", $sprite="kubernetes") {
    Container(prometheus, "Prometheus", "", "", $sprite="prometheus", $tags="prometheus")
    Container(kepler, "Kepler", "", "", $sprite="day_sunny", $tags="kepler")

    Container(load_balancer, "Load Balancer", "", $sprite="KubernetesSvc", $tags="k8s")

    Boundary(sut, "System under Test", $tags="sut") {
        Container(t2_project, "T2-Project\nBackend", "", "", $sprite="mug_hot")
    }

    Container(hpa, "Autoscaler", "", $sprite="KubernetesHpa", $tags="k8s")
}

Rel(jmeter, load_balancer, "1. Executes\nAPI requests")
Rel(load_balancer, t2_project, "2. Forwards\nrequests to", "")

Rel_D(hpa, t2_project, "Scales\ndeployments")
Rel_D(prometheus, kepler, "4. Scrapes\ndata from")
Rel_R(kepler, t2_project, "\n3. Estimates\npower\nconsumption\nof")

@enduml
